## Homework 2 Solution

In [1]:
#Geometry Analysis Soultion

In [2]:
import numpy
import os

In [3]:
#open file
file_location = os.path.join('data','water.xyz')
print(file_location)

data/water.xyz


In [4]:
#read info in file--> tabular data numpy.genfromtxt
#delimiter separation by space = default 
#mixed data = unicode
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode')

ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 1)
    Line #3 (got 4 columns instead of 1)
    Line #4 (got 4 columns instead of 1)
    Line #5 (got 4 columns instead of 1)

In [5]:
#numpy output-array/matrix
#error-different number of columns --> skip over header
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header = 2)

In [6]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [7]:
#separate out symbols and numbers by slicing 
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
print(symbols)
print(coordinates)

['O' 'H1' 'H2']
[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [8]:
#overwrite existing coordinates (assign type) ''--> informing you it's strings
coordinates = coordinates.astype(numpy.float)
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [9]:
#measuring the distance between all the atoms 
#$$ equation in markdown

$$ distance= \sqrt((x1-x2)^2 + (y1-y2)^2 + (z1-z2)^2) $$

In [17]:
#for loop: each atom have a turn at being atom 1 and 2
#outer for loop: be atom 1 and every atom can be this 
#inner loop: counts over atom 2 and every atom gets this chance
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        distance_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {distance_12}')

O to O : 0.0
O to H1 : 0.9690005374652793
O to H2 : 0.9690003348647513
H1 to O : 0.9690005374652793
H1 to H1 : 0.0
H1 to H2 : 1.52693633514957
H2 to O : 0.9690003348647513
H2 to H1 : 1.52693633514957
H2 to H2 : 0.0


In [21]:
symbols = xyz_file[:,0]

num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        #print(F'Atom 1 is{num1}')
        #print(F'Atom 2 is{num2}')
        if num1<num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            distance_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [22]:
import numpy
import os

file_location = os.path.join('data','water.xyz')

xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header = 2)
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)

num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
                x_distance = coordinates[num1,0] - coordinates[num2,0]
                y_distance = coordinates[num1,1] - coordinates[num2,1]
                z_distance = coordinates[num1,2] - coordinates[num2,2]
                distance_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
                if distance_12 > 0 and distance_12 <= 1.5:
                    print(F'{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969
